# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and Test (humble)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup ROS environment
      # You may pin to the exact commit or the version.
      # uses: ros-tooling/setup-ros@5e42c2faf543cbcc67f90432d54035cc2c188f97
      uses: ros-tooling/setup-ros@0.5.1
      with:
        required-ros-distributions: humble

    - name: Build
      uses: ros-tooling/action-ros-ci@0.3.5
      with:
        package-name: irm_detection
        target-ros2-distro: humble
        skip-tests: true
